# Generated by Django 5.2.17 on 2026-10-05 09:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='document_back',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.kyc_document_upload_path),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_front',
            field=models.FileField(upload_to=accounts.models.kyc_document_upload_path),
        ),
    ]
