# Generated by Django 5.2.17 on 2026-10-05 08:26

from django.db import migrations, models


def migrate_legacy_booking_statuses(apps, schema_editor):
    Booking = apps.get_model("bookings", "ProjectBooking")
    mapping = {
        "COUNTER_OFFERED": "COUNTER_OFFER",
        "AGREEMENT_REACHED": "AGREEMENT",
        "DELIVERABLE_SUBMITTED": "DELIVERABLE_SENT",
        "CLIENT_REVIEWING": "DELIVERABLE_SENT",
    }
    for old, new in mapping.items():
        Booking.objects.filter(status=old).update(status=new)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_revisionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='counteroffer',
            name='additional_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='counteroffer',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counteroffer',
            name='revision_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counteroffer',
            name='scope',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='projectbooking',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectbooking',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.RunPython(migrate_legacy_booking_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='projectbooking',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PROVIDER_RESPONSE', 'Pending provider response'), ('COUNTER_OFFER', 'Counter offer'), ('AGREEMENT', 'Agreement'), ('PAYMENT_PENDING', 'Payment pending'), ('PAYMENT_FAILED', 'Payment failed'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In progress'), ('DELIVERABLE_SENT', 'Deliverable sent'), ('REVISION_REQUESTED', 'Revision requested'), ('COMPLETED', 'Completed'), ('REVIEWED', 'Reviewed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('DISPUTED', 'Disputed')], default='PENDING_PROVIDER_RESPONSE', max_length=40),
        ),
    ]
