# Generated by Django 5.2.17 on 2026-10-05 08:26

from django.db import migrations, models


def initialize_service_status(apps, schema_editor):
    Service = apps.get_model("catalog", "Service")
    for service in Service.objects.all().only("id", "is_active"):
        service.status = "PUBLISHED" if service.is_active else "INACTIVE"
        service.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=16),
        ),
        migrations.RunPython(initialize_service_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
